blank_issues_enabled: false
contact_links:
  - name: 🐞 Bug Tracker Remnawave
    url: https://f.docs.rw/c/bug-reports/13
    about: Report a bug — here
  - name: 💡 Feature Request Remnawave
    url: https://f.docs.rw/c/fr/7
    about: Suggest a feature — here
